project:
  type: website

website:
  title: "Ivan Anokhin"
  description: "PhD student at Mila."
  navbar:
    left:
      - text: About
        href: index.qmd
      - text: Publications
        href: publications.qmd
      - text: Blog
        href: posts/
    right:
      - icon: github
        href: https://github.com/avecplezir
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=CJ-86AYAAAAJ&hl=en&oi=ao
      - icon: mail
        href: mailto:i.anokhin.mm@gmail.com
  page-footer:
    left: "© {2025} Ivan Anokhin"
    right: "Built with Quarto"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    smooth-scroll: true
    code-fold: show
    grid:
      body-width: 900px
      sidebar-width: 300px

metadata:
  image: images/me.jpg
  lang: en

execute:
  freeze: auto
